// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://dummy.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'dummykey';

const client = (window as any).supabase ?? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});

if (import.meta.env.DEV) {
    (window as any).supabase = client;
}

export const supabase = client;